name: projetomobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.2.0  
  barcode_scan2: ^4.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  path_provider: ^2.1.4
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  google_maps_flutter: ^2.2.3
  mobile_scanner: ^6.0.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/visionPlusIcon.png